using System;
using System.Threading;
using Cysharp.Threading.Tasks;
using UnityEngine;
using UnityEngine.Assertions;

namespace Citadel.Game
{
    internal interface IResourcesLoader : IDisposable
    {
        UniTask<T> LoadAssetAsync<T>(string assetName, CancellationToken cancellationToken)
            where T : UnityEngine.Object;

        UniTask<GameObject> InstantiateAsync(string assetName, Vector3 position, Quaternion rotation,
            Transform parentTransform, CancellationToken cancellationToken);

        void ReleaseAsset(string assetName);

        void ReleaseAllAssets();
    }

    internal static class IResourcesLoaderExtensions
    {
        public static UniTask<T> LoadAssetAsync<T>(this IResourcesLoader resourcesLoader, string assetName)
            where T : UnityEngine.Object
        {
            return resourcesLoader.LoadAssetAsync<T>(assetName, CancellationToken.None);
        }

        public static UniTask<GameObject> InstantiateAsync(this IResourcesLoader resourcesLoader, string assetName,
            Vector3 position,
            Quaternion rotation, Transform parentTransform = null)
        {
            return resourcesLoader.InstantiateAsync(assetName, position, rotation, parentTransform,
                CancellationToken.None);
        }

        public static async UniTaskVoid LoadAssetAsync<T>(this IResourcesLoader resourcesLoader, string assetName,
            Action<T> onAssetLoaded) where T : UnityEngine.Object
        {
            if (string.IsNullOrEmpty(assetName))
            {
                throw new ArgumentNullException(nameof(assetName));
            }

            Assert.IsNotNull(onAssetLoaded);

            T loadedAsset = await resourcesLoader.LoadAssetAsync<T>(assetName);
            onAssetLoaded(loadedAsset);
        }

        public static async UniTaskVoid InstantiateAsync(this IResourcesLoader resourcesLoader, string assetName,
            Vector3 position, Quaternion rotation, Transform parentTransform, Action<GameObject> onPrefabInstantiated)
        {
            if (string.IsNullOrEmpty(assetName))
            {
                throw new ArgumentNullException(nameof(assetName));
            }

            Assert.IsNotNull(onPrefabInstantiated);

            GameObject instantiatedPrefab =
                await resourcesLoader.InstantiateAsync(assetName, position, rotation, parentTransform);
            onPrefabInstantiated(instantiatedPrefab);
        }

        public static void InstantiateAsync(this IResourcesLoader resourcesLoader, string assetName,
            Vector3 position, Quaternion rotation, Action<GameObject> onPrefabInstantiated)
        {
            resourcesLoader.InstantiateAsync(assetName, position, rotation, null, onPrefabInstantiated);
        }

        public static async UniTaskVoid InstantiatePrefabAsync(this IResourcesLoader resourcesLoader, int prefabIndex, 
            Vector3 position, Quaternion rotation, Transform parentTransform, Action<GameObject> onPrefabInstantiated)
        {
            Assert.IsNotNull(onPrefabInstantiated);
            var result = await resourcesLoader.InstantiatePrefabAsync(prefabIndex, position, rotation, parentTransform);
            onPrefabInstantiated(result);
        }
        
        public static UniTask<GameObject> InstantiatePrefabAsync(this IResourcesLoader resourcesLoader, int prefabIndex, 
            Vector3 position, Quaternion rotation, Transform parentTransform = null)
        {
            const int maxPrefabIndex = 748;
            return prefabIndex < maxPrefabIndex ? resourcesLoader.InstantiateAsync(GetPrefabNameFromIndex(prefabIndex), position, rotation, parentTransform) : 
                UniTask.FromResult<GameObject>(null);
        }
        
        private static string GetPrefabNameFromIndex(int constIndex)
        {
            switch (constIndex)
            {
                case 0: return "chunk_black";
                case 1: return "chunk_blocker";
                case 2: return "chunk_bridg1_1";
                case 3: return "chunk_bridg1_1flipx";
                case 4: return "chunk_bridg1_2";
                case 5: return "chunk_bridg1_3";
                case 6: return "chunk_bridg1_3_slice45";
                case 7: return "chunk_bridg1_3flipx";
                case 8: return "chunk_bridg1_4";
                case 9: return "chunk_bridg1_4_slice32";
                case 10: return "chunk_bridg1_4_slice32flipx";
                case 11: return "chunk_bridg1_5";
                case 12: return "chunk_bridg2_2";
                case 13: return "chunk_bridg2_3";
                case 14: return "chunk_bridg2_4";
                case 15: return "chunk_bridg2_5";
                case 16: return "chunk_bridg2_6";
                case 17: return "chunk_bridg2_7";
                case 18: return "chunk_bridg2_8";
                case 19: return "chunk_bridg2_9";
                case 20: return "chunk_crate_impenetrable";
                case 21: return "chunk_cyberpanel";
                case 22: return "chunk_cyberpanel_slice45";
                case 23: return "chunk_eng1_1";
                case 24: return "chunk_eng1_1d";
                case 25: return "chunk_eng1_2";
                case 26: return "chunk_eng1_2d";
                case 27: return "chunk_eng1_3";
                case 28: return "chunk_eng1_3d";
                case 29: return "chunk_eng1_4";
                case 30: return "chunk_eng1_5";
                case 31: return "chunk_eng1_5_slice45lh";
                case 32: return "chunk_eng1_5_slice45rh";
                case 33: return "chunk_eng1_5d";
                case 34: return "chunk_eng1_6";
                case 35: return "chunk_eng1_6d";
                case 36: return "chunk_eng1_7";
                case 37: return "chunk_eng1_7d";
                case 38: return "chunk_eng1_8";
                case 39: return "chunk_eng1_9";
                case 40: return "chunk_eng1_9d";
                case 41: return "chunk_eng2_1";
                case 42: return "chunk_eng2_1_slice45";
                case 43: return "chunk_eng2_1_slice384high";
                case 44: return "chunk_eng2_1_slice384highrh";
                case 45: return "chunk_eng2_1d";
                case 46: return "chunk_eng2_2";
                case 47: return "chunk_eng2_2d";
                case 48: return "chunk_eng2_3";
                case 49: return "chunk_eng2_3d";
                case 50: return "chunk_eng2_4";
                case 51: return "chunk_eng2_5";
                case 52: return "chunk_eng2_5_slice45";
                case 53: return "chunk_eng2_6";
                case 54: return "chunk_exec1_1";
                case 55: return "chunk_exec1_1d";
                case 56: return "chunk_exec1_2";
                case 57: return "chunk_exec1_2d";
                case 58: return "chunk_exec2_1";
                case 59: return "chunk_exec2_2";
                case 60: return "chunk_exec2_2d";
                case 61: return "chunk_exec2_3";
                case 62: return "chunk_exec2_4";
                case 63: return "chunk_exec2_4_slice45";
                case 64: return "chunk_exec2_5";
                case 65: return "chunk_exec2_6";
                case 66: return "chunk_exec2_7";
                case 67: return "chunk_exec3_1";
                case 68: return "chunk_exec3_1d";
                case 69: return "chunk_exec3_2";
                case 70: return "chunk_exec3_4";
                case 71: return "chunk_exec4_1";
                case 72: return "chunk_exec4_2";
                case 73: return "chunk_exec4_3";
                case 74: return "chunk_exec4_4";
                case 75: return "chunk_exec4_5";
                case 76: return "chunk_exec4_6";
                case 77: return "chunk_exec6_1";
                case 78: return "chunk_exteriorpanel1";
                case 79: return "chunk_fan1";
                case 80: return "chunk_flight1_1";
                case 81: return "chunk_flight1_1b";
                case 82: return "chunk_flight1_2";
                case 83: return "chunk_flight1_2_slice45rh";
                case 84: return "chunk_flight1_3";
                case 85: return "chunk_flight1_4";
                case 86: return "chunk_flight1_5";
                case 87: return "chunk_flight1_5_slice45lh";
                case 88: return "chunk_flight1_6";
                case 89: return "chunk_flight2_1";
                case 90: return "chunk_flight2_2";
                case 91: return "chunk_flight2_2_slice45";
                case 92: return "chunk_flight2_3";
                case 93: return "chunk_grove1_1";
                case 94: return "chunk_grove1_2";
                case 95: return "chunk_grove1_2_slice45";
                case 96: return "chunk_grove1_3";
                case 97: return "chunk_grove1_4";
                case 98: return "chunk_grove1_5";
                case 99: return "chunk_grove1_6";
                case 100: return "chunk_grove1_7";
                case 101: return "chunk_grove2_1";
                case 102: return "chunk_grove2_2";
                case 103: return "chunk_grove2_3";
                case 104: return "chunk_grove2_4";
                case 105: return "chunk_grove2_5";
                case 106: return "chunk_grove2_6";
                case 107: return "chunk_grove2_7";
                case 108: return "chunk_grove2_8";
                case 109: return "chunk_grove2_9";
                case 110: return "chunk_grove2_9b";
                case 111: return "chunk_grove2_9c";
                case 112: return "chunk_lift1";
                case 113: return "chunk_maint1_1";
                case 114: return "chunk_maint1_2";
                case 115: return "chunk_maint1_2d";
                case 116: return "chunk_maint1_3";
                case 117: return "chunk_maint1_3b";
                case 118: return "chunk_maint1_4";
                case 119: return "chunk_maint1_4b";
                case 120: return "chunk_maint1_5";
                case 121: return "chunk_maint1_6";
                case 122: return "chunk_maint1_7";
                case 123: return "chunk_blockerflightbay";
                case 124: return "chunk_maint1_9";
                case 125: return "chunk_maint1_9d";
                case 126: return "chunk_maint2_1";
                case 127: return "chunk_maint2_1b";
                case 128: return "chunk_maint2_1d";
                case 129: return "chunk_maint2_2";
                case 130: return "chunk_maint2_3";
                case 131: return "chunk_maint2_3d";
                case 132: return "chunk_maint2_4";
                case 133: return "chunk_maint2_4d";
                case 134: return "chunk_maint2_5";
                case 135: return "chunk_maint2_5d";
                case 136: return "chunk_maint2_6";
                case 137: return "chunk_maint2_6d";
                case 138: return "chunk_maint2_7";
                case 139: return "chunk_maint2_7d";
                case 140: return "chunk_maint2_8";
                case 141: return "chunk_maint2_9";
                case 142: return "chunk_maint2_9_slice45RH";
                case 143: return "chunk_maint2_9_slice128_top";
                case 144: return "chunk_maint3_1";
                case 145: return "chunk_maint3_1_slice32_lh";
                case 146: return "chunk_maint3_1_slice32_rh";
                case 147: return "chunk_maint3_1_slice45";
                case 148: return "chunk_maint3_1d";
                case 149: return "chunk_med1_1";
                case 150: return "chunk_med1_1_half_top";
                case 151: return "chunk_med1_1_slice128high";
                case 152: return "chunk_med1_1_slice192RH";
                case 153: return "chunk_med1_1_slice256";
                case 154: return "chunk_med1_1d";
                case 155: return "chunk_med1_2";
                case 156: return "chunk_med1_2d";
                case 157: return "chunk_med1_3";
                case 158: return "chunk_med1_3d";
                case 159: return "chunk_med1_4";
                case 160: return "chunk_med1_5";
                case 161: return "chunk_med1_6";
                case 162: return "chunk_med1_7";
                case 163: return "chunk_med1_7_slice14_64";
                case 164: return "chunk_med1_7_slice45_320lh";
                case 165: return "chunk_med1_7_slice45_320rh";
                case 166: return "chunk_med1_7_slice96high";
                case 167: return "chunk_med1_7d";
                case 168: return "chunk_med1_7d_slice128";
                case 169: return "chunk_med1_8";
                case 170: return "chunk_med1_8d";
                case 171: return "chunk_med1_9";
                case 172: return "chunk_black";
                case 173: return "chunk_black";
                case 174: return "chunk_med1_9d";
                case 175: return "chunk_black";
                case 176: return "chunk_med1_9d_ofs112_90";
                case 177: return "chunk_med1_9d_ofs144_90";
                case 178: return "chunk_med2_1";
                case 179: return "chunk_med2_1_slice32RH";
                case 180: return "chunk_med2_1d";
                case 181: return "chunk_med2_2";
                case 182: return "chunk_med2_2_half_bottom";
                case 183: return "chunk_med2_2d";
                case 184: return "chunk_med2_3";
                case 185: return "chunk_med2_3d";
                case 186: return "chunk_med2_4";
                case 187: return "chunk_med2_5";
                case 188: return "chunk_med2_6";
                case 189: return "chunk_med2_7";
                case 190: return "chunk_med2_8";
                case 191: return "chunk_med2_8_half_top";
                case 192: return "chunk_med2_8_slice32RH";
                case 193: return "chunk_med2_8_slice45";
                case 194: return "chunk_med2_9";
                case 195: return "chunk_med2_9d";
                case 196: return "chunk_med3_1";
                case 197: return "chunk_rad1_1";
                case 198: return "chunk_rad1_2";
                case 199: return "chunk_reac1_1";
                case 200: return "chunk_reac1_1_slice45";
                case 201: return "chunk_reac1_2";
                case 202: return "chunk_reac1_3";
                case 203: return "chunk_reac1_4";
                case 204: return "chunk_reac1_5";
                case 205: return "chunk_reac1_6";
                case 206: return "chunk_reac1_7";
                case 207: return "chunk_reac1_8";
                case 208: return "chunk_reac1_9";
                case 209: return "chunk_reac2_1";
                case 210: return "chunk_reac2_1_slice45LH";
                case 211: return "chunk_reac2_1_slice45LH_up";
                case 212: return "chunk_reac2_1_slice45RH";
                case 213: return "chunk_reac2_1_slice45RH_up";
                case 214: return "chunk_reac2_1b";
                case 215: return "chunk_reac2_1bmirror";
                case 216: return "chunk_reac2_1mirror";
                case 217: return "chunk_reac2_2";
                case 218: return "chunk_reac2_4";
                case 219: return "chunk_reac2_4_slice128lower";
                case 220: return "chunk_reac2_5";
                case 221: return "chunk_reac2_6";
                case 222: return "chunk_reac2_7";
                case 223: return "chunk_reac2_8";
                case 224: return "chunk_reac2_9";
                case 225: return "chunk_reac3_1";
                case 226: return "chunk_reac3_2";
                case 227: return "chunk_reac3_3";
                case 228: return "chunk_reac3_4";
                case 229: return "chunk_reac3_5";
                case 230: return "chunk_reac3_6";
                case 231: return "chunk_reac3_7";
                case 232: return "chunk_reac4_1";
                case 233: return "chunk_reac4_1_slice45lh";
                case 234: return "chunk_reac4_2";
                case 235: return "chunk_reac5_1";
                case 236: return "chunk_reac5_2";
                case 237: return "chunk_reac5_3";
                case 238: return "chunk_reac6_1";
                case 239: return "chunk_reac6_2";
                case 240: return "chunk_reac6_3";
                case 241: return "chunk_sci1_1";
                case 242: return "chunk_sci1_1_slice45_toplh";
                case 243: return "chunk_sci1_1_slice45_toprh";
                case 244: return "chunk_sci1_1d";
                case 245: return "chunk_sci1_2";
                case 246: return "chunk_sci1_2_slice45lh";
                case 247: return "chunk_sci1_2_slice45lh_up";
                case 248: return "chunk_sci1_2_slice45rh";
                case 249: return "chunk_sci1_2_slice45rh_up";
                case 250: return "chunk_sci1_2d";
                case 251: return "chunk_sci1_3";
                case 252: return "chunk_sci1_4";
                case 253: return "chunk_sci1_5";
                case 254: return "chunk_sci1_6";
                case 255: return "chunk_sci1_6_slice45";
                case 256: return "chunk_sci1_7";
                case 257: return "chunk_sci1_7d";
                case 258: return "chunk_sci1_8";
                case 259: return "chunk_sci1_8d";
                case 260: return "chunk_sci1_9";
                case 261: return "chunk_sci1_9d";
                case 262: return "chunk_sci2_1";
                case 263: return "chunk_sci2_1_slice45lh";
                case 264: return "chunk_sci2_1_slice45rh";
                case 265: return "chunk_sci2_1d";
                case 266: return "chunk_sci2_2";
                case 267: return "chunk_sci2_2d";
                case 268: return "chunk_sci2_3";
                case 269: return "chunk_sci2_4";
                case 270: return "chunk_sci2_5";
                case 271: return "chunk_sci2_5d";
                case 272: return "chunk_sci3_1";
                case 273: return "chunk_sci3_1d";
                case 274: return "chunk_sci3_2";
                case 275: return "chunk_sci3_3";
                case 276: return "chunk_sci3_4";
                case 277: return "chunk_sci3_5";
                case 278: return "chunk_sci3_6";
                case 279: return "chunk_screen";
                case 280: return "chunk_sec1_1";
                case 281: return "chunk_sec1_1b";
                case 282: return "chunk_sec1_1c";
                case 283: return "chunk_sec1_1c_slice45";
                case 284: return "chunk_sec1_1c_slice64highlh";
                case 285: return "chunk_sec1_1c_slice64highrh";
                case 286: return "chunk_black";
                case 287: return "chunk_black";
                case 288: return "chunk_sec1_2";
                case 289: return "chunk_sec1_2b";
                case 290: return "chunk_sec1_3";
                case 291: return "chunk_sec1_3_slice45";
                case 292: return "chunk_stor1_1";
                case 293: return "chunk_stor1_2";
                case 294: return "chunk_stor1_3";
                case 295: return "chunk_stor1_4";
                case 296: return "chunk_stor1_5";
                case 297: return "chunk_stor1_6";
                case 298: return "chunk_stor1_6_slice128_up_lh";
                case 299: return "chunk_stor1_6_slice128_up_rh";
                case 300: return "chunk_stor1_6_slice192lh";
                case 301: return "chunk_stor1_6_slice192rh";
                case 302: return "chunk_stor1_7";
                case 303: return "chunk_stor1_7_slice45";
                case 304: return "chunk_stor1_7d";
                case 305: return "chunk_teleporter";
                case 306: return "chunk_white";
                case 307: return "item_paper_wad";
                case 308: return "item_warecasing";
                case 309: return "item_beaker";
                case 310: return "item_beverage";
                case 311: return "item_skull";
                case 312: return "item_arm";
                case 313: return "item_audiolog";
                case 314: return "weapon_grenadefrag";
                case 315: return "weapon_grenadeconc";
                case 316: return "weapon_grenadeemp";
                case 317: return "weapon_grenadeearth";
                case 318: return "weapon_grenademine";
                case 319: return "weapon_grenadenitro";
                case 320: return "weapon_grenadegas";
                case 321: return "item_patch_berserk";
                case 322: return "item_patch_detox";
                case 323: return "item_patch_genius";
                case 324: return "item_patch_medi";
                case 325: return "item_patch_reflex";
                case 326: return "item_patch_sight";
                case 327: return "item_patch_staminup";
                case 328: return "item_hw_system";
                case 329: return "item_hw_navunit";
                case 330: return "item_hw_ereader";
                case 331: return "item_hw_sensaround";
                case 332: return "item_hw_targetid";
                case 333: return "item_hw_shield";
                case 334: return "item_hw_bio";
                case 335: return "item_hw_lantern";
                case 336: return "item_hw_envirosuit";
                case 337: return "item_hw_booster";
                case 338: return "item_hw_jumpjets";
                case 339: return "item_hw_infrared";
                case 340: return "item_fireextinguisher";
                case 341: return "item_access_card_admin";
                case 342: return "item_workerhelmet";
                case 343: return "weapon_mk3";
                case 344: return "weapon_blaster";
                case 345: return "weapon_dartgun";
                case 346: return "weapon_flechette";
                case 347: return "weapon_ionrifle";
                case 348: return "weapon_rapier";
                case 349: return "weapon_pipe";
                case 350: return "weapon_magnum";
                case 351: return "weapon_magpulse";
                case 352: return "weapon_pistol";
                case 353: return "weapon_plasma";
                case 354: return "weapon_railgun";
                case 355: return "weapon_riotgun";
                case 356: return "weapon_skorpion";
                case 357: return "weapon_sparqbeam";
                case 358: return "weapon_stungun";
                case 359: return "item_battery";
                case 360: return "item_battery_icad";
                case 361: return "item_logic_probe";
                case 362: return "item_healthkit";
                case 363: return "item_plastique";
                case 364: return "item_chipset_interfacedemod";
                case 365: return "item_flask";
                case 366: return "item_chipset_bitflag";
                case 367: return "item_ammo_rubber";
                case 368: return "item_isotopex22";
                case 369: return "item_testtube";
                case 370: return "weapon_grenadefrag_live";
                case 371: return "item_chipset_isolinear";
                case 372: return "weapon_grenadeconc_live";
                case 373: return "item_ammo_needle";
                case 374: return "item_ammo_tranq";
                case 375: return "item_ammo_standard";
                case 376: return "item_ammo_teflon";
                case 377: return "item_ammo_hollow";
                case 378: return "item_ammo_slug";
                case 379: return "item_ammo_magnesium";
                case 380: return "item_ammo_penetrator";
                case 381: return "item_ammo_hornet";
                case 382: return "item_ammo_splinter";
                case 383: return "item_ammo_rail";
                case 384: return "item_ammo_slag";
                case 385: return "item_ammo_slaglarge";
                case 386: return "item_ammo_magcart";
                case 387: return "weapon_grenadeemp_live";
                case 388: return "item_access_card_std";
                case 389: return "weapon_grenadeearth_live";
                case 390: return "item_access_card_group1";
                case 391: return "item_access_card_science";
                case 392: return "item_access_card_eng";
                case 393: return "item_access_card_groupB";
                case 394: return "item_access_card_security";
                case 395: return "item_access_card_per5diego";
                case 396: return "item_access_card_medi";
                case 397: return "item_access_card_group3";
                case 398: return "item_access_card_purple";
                case 399: return "item_head_male";
                case 400: return "item_head_female";
                case 401: return "item_severedhead";
                case 402: return "weapon_grenademine_live";
                case 403: return "weapon_grenadenitro_live";
                case 404: return "weapon_grenadegas_live";
                case 405: return "line_sparqbeam";
                case 406: return "line_blaster";
                case 407: return "line_ion";
                case 408: return "line_hopperbeam";
                case 409: return "red crosshair";
                case 410: return "orange crosshair";
                case 411: return "yellow crosshair";
                case 412: return "green crosshair small";
                case 413: return "teal crosshair";
                case 414: return "blue crosshair";
                case 415: return "cursor vmail";
                case 416: return "cursor cyberspace";
                case 417: return "item_access_card_perdarcy";
                case 418: return "null";
                case 419: return "npc_autobomb";
                case 420: return "npc_cyborg_assassin";
                case 421: return "npc_avian_mutant";
                case 422: return "npc_exec_bot";
                case 423: return "npc_cyborg_drone";
                case 424: return "npc_cortex_reaver";
                case 425: return "npc_cyborg_warrior";
                case 426: return "npc_cyborg_enforcer";
                case 427: return "npc_cyborg_elite";
                case 428: return "npc_cyborg_diego";
                case 429: return "npc_sec1_bot";
                case 430: return "npc_sec2_bot";
                case 431: return "npc_maint_bot";
                case 432: return "npc_mutant_cyborg";
                case 433: return "npc_hopper";
                case 434: return "npc_humanoid_mutant";
                case 435: return "npc_invisomut";
                case 436: return "npc_virus_mutant";
                case 437: return "npc_servbot";
                case 438: return "npc_flier_bot";
                case 439: return "npc_zerog_mutant";
                case 440: return "npc_gorilla_tiger_mutant";
                case 441: return "npc_repairbot";
                case 442: return "npc_plant_mutant";
                case 443: return "npc_cyberdog";
                case 444: return "npc_cyberguard";
                case 445: return "npc_cyberram";
                case 446: return "npc_cyber_reaver";
                case 447: return "npc_cybershodan";
                case 448: return "item_cyber_data";
                case 449: return "item_cyber_decoy";
                case 450: return "item_cyber_drill";
                case 451: return "item_cyber_game";
                case 452: return "item_cyber_integrity";
                case 453: return "item_cyber_keycard";
                case 454: return "item_cyber_pulser";
                case 455: return "item_cyber_recall";
                case 456: return "item_cyber_shield";
                case 457: return "item_cyber_turbo";
                case 458: return "prop_phys_barrel_chemical";
                case 459: return "prop_phys_barrel_radiation";
                case 460: return "prop_phys_barrel_toxic";
                case 461: return "prop_phys_cart";
                case 462: return "prop_phys_pot";
                case 463: return "prop_phys_toolcart";
                case 464: return "se_briefcase";
                case 465: return "se_corpse_blueshirt";
                case 466: return "se_corpse_brownshirt";
                case 467: return "se_corpse_eaten";
                case 468: return "se_corpse_labcoat";
                case 469: return "se_corpse_security";
                case 470: return "se_corpse_tan";
                case 471: return "se_corpse_torso";
                case 472: return "se_crate1";
                case 473: return "se_crate2";
                case 474: return "se_crate3";
                case 475: return "se_crate4";
                case 476: return "se_crate5";
                case 477: return "sec_camera";
                case 478: return "sec_cpunode";
                case 479: return "sec_cpunode_small";
                case 480: return "weapon_cyber_mine";
                case 481: return "proj_enemshot2";
                case 482: return "proj_magpulse_shot";
                case 483: return "proj_stungun_shot";
                case 484: return "proj_rail_shot";
                case 485: return "proj_plasmarifle_shot";
                case 486: return "proj_enemshot6";
                case 487: return "proj_enemshot5";
                case 488: return "proj_enemshot4";
                case 489: return "proj_throwingstar";
                case 490: return "proj_magpulsenpc_shot";
                case 491: return "proj_railnpc_shot";
                case 492: return "proj_cyberplayer_shot";
                case 493: return "proj_cyberdog_shot";
                case 494: return "proj_cyberreaver_shot";
                case 495: return "proj_cyberice_shot";
                case 496: return "doorA";
                case 497: return "doorB";
                case 498: return "doorC";
                case 499: return "doorD";
                case 500: return "doorE";
                case 501: return "doorF";
                case 502: return "doorG";
                case 503: return "doorH";
                case 504: return "doorI";
                case 505: return "doorJ";
                case 506: return "doorK";
                case 507: return "doorL";
                case 508: return "door_elevator1";
                case 509: return "door_elevator2";
                case 510: return "door_elevator3";
                case 511: return "door_elevator4";
                case 512: return "door_secret1";
                case 513: return "door_secret2";
                case 514: return "door_secret3";
                case 515: return "func_forcebridge";
                case 516: return "prop_lift2";
                case 517: return "func_wall";
                case 518: return "BulletHoleLarge";
                case 519: return "BulletHoleScorchLarge";
                case 520: return "BulletHoleScorchSmall";
                case 521: return "BulletHoleSmall";
                case 522: return "BulletHoleTiny";
                case 523: return "BulletHoleTinySpread";
                case 524: return "func_door_cyber";
                case 525: return "prop_console01";
                case 526: return "prop_console02";
                case 527: return "prop_grate1_1";
                case 528: return "prop_grate1_2";
                case 529: return "prop_grate1_3";
                case 530: return "se_cabinet";
                case 531: return "se_thermos";
                case 532: return "prop_beaker_holder";
                case 533: return "prop_bed";
                case 534: return "prop_bed_hospital";
                case 535: return "prop_bed_neurosurgery";
                case 536: return "prop_bonepile1";
                case 537: return "prop_bridgewall1";
                case 538: return "prop_broken_clock";
                case 539: return "prop_brokengun";
                case 540: return "prop_chair01";
                case 541: return "prop_chair02";
                case 542: return "prop_chair03";
                case 543: return "prop_chair04";
                case 544: return "prop_chair05";
                case 545: return "prop_chandelier";
                case 546: return "prop_charge_station";
                case 547: return "prop_clothes";
                case 548: return "prop_computer";
                case 549: return "prop_couch";
                case 550: return "prop_couch2";
                case 551: return "prop_cpuscreen";
                case 552: return "prop_cyber_datafrag";
                case 553: return "prop_cyber_decoy";
                case 554: return "prop_cyber_exit";
                case 555: return "prop_cyber_switch";
                case 556: return "prop_cyberport";
                case 557: return "prop_desk01";
                case 558: return "prop_desk02";
                case 559: return "prop_dexmissile";
                case 560: return "prop_foliage_fernpoison";
                case 561: return "prop_foliage_bush";
                case 562: return "prop_foliage_fern";
                case 563: return "prop_foliage_fernblueflower";
                case 564: return "prop_foliage_pinetreem";
                case 565: return "prop_foliage_poisonbush1";
                case 566: return "prop_gear_large";
                case 567: return "prop_gear_small";
                case 568: return "prop_grass1";
                case 569: return "prop_grass2";
                case 570: return "prop_grass3";
                case 571: return "prop_grass4";
                case 572: return "prop_grass5";
                case 573: return "prop_grate4";
                case 574: return "prop_healingbed";
                case 575: return "prop_lamp";
                case 576: return "prop_light_emergsignal";
                case 577: return "prop_microscope";
                case 578: return "prop_pipe";
                case 579: return "prop_puddle";
                case 580: return "prop_puddle_grease";
                case 581: return "prop_puddle_oil";
                case 582: return "prop_shelves";
                case 583: return "prop_skeleton";
                case 584: return "prop_sleeping_cables";
                case 585: return "prop_sparkingwire";
                case 586: return "prop_table";
                case 587: return "prop_tv_on_a_post";
                case 588: return "prop_vendingmachines1";
                case 589: return "prop_vendingmachines2";
                case 590: return "prop_weapon_rack";
                case 591: return "prop_xray";
                case 592: return "text_decal";
                case 593: return "text_decalStopDSS1";
                case 594: return "trigger_counter";
                case 595: return "trigger_cyberpush";
                case 596: return "trigger_gravitylift";
                case 597: return "trigger_ladder";
                case 598: return "trigger_multiple";
                case 599: return "trigger_music";
                case 600: return "trigger_once";
                case 601: return "trigger_radiation";
                case 602: return "us_isotopepanel";
                case 603: return "us_paperlog";
                case 604: return "us_puz_elevatorkeypad";
                case 605: return "us_puz_elevatorkeypad2";
                case 606: return "us_puz_elevatorkeypad3";
                case 607: return "us_puz_elevatorkeypad4";
                case 608: return "us_puz_keypad";
                case 609: return "us_puz_panel_blue_grid";
                case 610: return "us_puz_panel_brown_grid";
                case 611: return "us_puz_panel_gray_grid";
                case 612: return "us_puz_panel_red_grid";
                case 613: return "us_puz_panel_teal_grid";
                case 614: return "us_relaypanel";
                case 615: return "us_retinalscanner";
                case 616: return "prop_vending1_1";
                case 617: return "prop_vending1_2";
                case 618: return "prop_vending1_3";
                case 619: return "prop_vending2_1";
                case 620: return "prop_vending2_2";
                case 621: return "ambient_airhiss";
                case 622: return "ambient_clicker";
                case 623: return "ambient_compressor";
                case 624: return "ambient_dishwasher";
                case 625: return "ambient_drip_amb";
                case 626: return "ambient_fan";
                case 627: return "ambient_generator_gas";
                case 628: return "ambient_gurgle";
                case 629: return "ambient_icemaker";
                case 630: return "ambient_intake";
                case 631: return "ambient_lathe";
                case 632: return "ambient_lev3loop1";
                case 633: return "ambient_lev3loop2";
                case 634: return "ambient_lev3loop3";
                case 635: return "ambient_lev3loop4";
                case 636: return "ambient_liquid_bubble";
                case 637: return "ambient_liquid_lava2";
                case 638: return "ambient_looping";
                case 639: return "ambient_machgear_loop";
                case 640: return "ambient_machine_ambience";
                case 641: return "ambient_machine_go";
                case 642: return "ambient_machine_humamb7";
                case 643: return "ambient_machine_humlonoise";
                case 644: return "ambient_machine_loop1";
                case 645: return "ambient_machine_loop2";
                case 646: return "ambient_machinea1";
                case 647: return "ambient_machinevat_loop";
                case 648: return "ambient_mist";
                case 649: return "ambient_pipewater_loop";
                case 650: return "ambient_powerloom";
                case 651: return "ambient_pump";
                case 652: return "ambient_pump2";
                case 653: return "ambient_rain";
                case 654: return "ambient_steam_loop";
                case 655: return "ambient_washing_machine";
                case 656: return "decal_blood_die";
                case 657: return "decal_blood_resist";
                case 658: return "decal_blood_stayaway";
                case 659: return "decal_blood_words2";
                case 660: return "decal_bloodfonta";
                case 661: return "decal_bloodfonte";
                case 662: return "decal_bloodfontg";
                case 663: return "decal_bloodfonth";
                case 664: return "decal_bloodfontr";
                case 665: return "decal_bloodfonty";
                case 666: return "decal_bloodsplat2";
                case 667: return "decal_logo_antenna";
                case 668: return "decal_logo_armory";
                case 669: return "decal_logo_biohazard";
                case 670: return "decal_logo_bridge";
                case 671: return "decal_logo_cyborg";
                case 672: return "decal_logo_gears";
                case 673: return "decal_logo_medical";
                case 674: return "decal_logo_radhazard";
                case 675: return "decal_logo_research";
                case 676: return "decal_logo_security";
                case 677: return "decal_painting1";
                case 678: return "decal_painting2";
                case 679: return "decal_painting3";
                case 680: return "decal_posterbetterfuture";
                case 681: return "decal_postergenetics";
                case 682: return "decal_scorch1";
                case 683: return "decal_scorch2";
                case 684: return "decal_scorch3";
                case 685: return "decal_scorch4";
                case 686: return "decal_scorchtiny";
                case 687: return "decal_blood_splat";
                case 688: return "func_switch1";
                case 689: return "func_switch2";
                case 690: return "func_switch3";
                case 691: return "func_switch4";
                case 692: return "func_switch5";
                case 693: return "func_switch5broken";
                case 694: return "func_switch7";
                case 695: return "func_switch8";
                case 696: return "func_switchbroken1";
                case 697: return "clip_npc";
                case 698: return "clip_objects";
                case 699: return "logic_relay";
                case 700: return "logic_branch";
                case 701: return "logic_timer";
                case 702: return "logic_spawner";
                case 703: return "info_teleport_destination";
                case 704: return "prop_debris_panel";
                case 705: return "info_cyborgconversion";
                case 706: return "info_elev_destination";
                case 707: return "info_email";
                case 708: return "info_gameend";
                case 709: return "info_message";
                case 710: return "info_mission";
                case 711: return "info_note";
                case 712: return "info_playsound";
                case 713: return "info_ressurection_point";
                case 714: return "info_screenshake";
                case 715: return "info_spawnpoint";
                case 716: return "fx_reverbzone";
                case 717: return "ef_cyber_ice";
                case 718: return "ef_fragexplosion";
                case 719: return "ef_line_sparqbeam";
                case 720: return "ef_mist";
                case 721: return "ef_particle_bloodspurtsmall";
                case 722: return "ef_particle_bloodspurtsmallgreen";
                case 723: return "ef_particle_bloodspurtsmallyellow";
                case 724: return "ef_particle_bloodspurttiny";
                case 725: return "ef_particle_camerahit";
                case 726: return "ef_particle_darthit";
                case 727: return "ef_particle_sec2muzburst";
                case 728: return "ef_particle_sec2rotmuzburst";
                case 729: return "ef_particle_sparksmall";
                case 730: return "ef_particle_sparksmallblue";
                case 731: return "ef_particle_sparqhit";
                case 732: return "ef_sparkspits";
                case 733: return "ef_spraydrips";
                case 734: return "ef_steam";
                case 735: return "env_sparksmall";
                case 736: return "TargetIDInstance";
                case 737: return "prop_papers01";
                case 738: return "prop_papers02";
                case 739: return "ef_particle_blasterhit";
                case 740: return "ef_particle_ionhit";
                case 741: return "us_puz_panel_blue_wire";
                case 742: return "us_puz_panel_brown_wire";
                case 743: return "us_puz_panel_gray_wire";
                case 744: return "us_puz_panel_red_wire";
                case 745: return "us_puz_panel_teal_wire";
                case 746: return "weapon_grenadeenergmine_live";
                case 747: return "decal_logo_storage";
            }

            return "item_paper_wad";
        }
    }
}